### ISSUE TITLE
implicit requirement of JAGS

### ISSUE THREAD

**Issue by spedygiorgio** [robjhyndman/demography#16]
When loading the demography package, the ftsa package is required but it appears to require an installation of JAGS 3.00 > on the user machines. Is there any way to remove such dependency (maybe not attaching the package on load)

**Comment by robjhyndman** [comment]
I can't control what ftsa loads. Talk to the maintainer of the ftsa package.

**Comment by robjhyndman** [comment]
The author of ftsa has agreed to remove this dependency. A new version of ftsa should be on CRAN in a day or two.
