### ISSUE TITLE
HMD now wrapped in SSL

### ISSUE THREAD

**Issue by carlboe** [robjhyndman/demography#31]
Rob,
The HMD website is now wrapped entirely in SSL so that passwords are no longer sent in the clear. 

As a result, code using RCurl with a URL of http://www.mortality.org  will get a 301 redirect returned, saying to use https://www.mortality.org    

In my experiment with local edits of your hmd.mx() function, just changing http:// to https:// seemed to return the expected results.

Regards,
Carl Boe,  HMD

**Comment by robjhyndman** [comment]
Fixed in https://github.com/robjhyndman/demography/commit/5b1e554974c80368da729a3f4ae038619f2ec9a2
