### ISSUE TITLE
Unable to download data from HMD

### ISSUE THREAD

**Issue by earthcat12** [robjhyndman/demography#32]
Hello, through my username and password i was able to download mortality data from HMD using `hmd.mx` there is a week now that i get the following error `Connection error at www.mortality.org. Please check username, password and country label.` I am sure that username and password is correct. Can you help me?

Thank you.

**Comment by robjhyndman** [comment]
Update to the new version on github. The problem is that HMD changed their URLs from http to https.

**Comment by earthcat12** [comment]
Thank you
