### ISSUE TITLE
Life Table

### ISSUE THREAD

**Issue by earthcat12** [robjhyndman/demography#33]
Hello, i have some models from the StMoMo package and i need to make lifetables from them. When i use the function `lifetable` i get the error that the data are not demogdata. Can you please help me?

My code is : ```
ages.fit<-55:89
wxt<- genWeightMat(ages = 55:89, years = grstomo.male$years, clip = 3)
rh<-rh(link = "log", cohortAgeFun = "1")
rhfit.male<- fit(rh, data = grstomo.male, ages.fit = ages.fit, wxt=wxt)
```

**Comment by robjhyndman** [comment]
Ask the maintainer of the StMoMo package. The `rh` and `genWeightMat` functions are not part of the demography package.
