### ISSUE TITLE
Newbie problem: can't load demography package

### ISSUE THREAD

**Issue by zaras86** [robjhyndman/demography#42]
when I try to load the package i get:

Load package: forecast
Error: package or namespace load failed for ‘demography’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
their is no package named ‘mclust’

I use R 3.5.3 on MacOs

I have no idea what to do.

**Comment by robjhyndman** [comment]
Read the error message. There is a missing package called `mclust`. So try to install that first.
