### ISSUE TITLE
Read dataset using `hmd`

### ISSUE THREAD

**Issue by vitaMiao** [robjhyndman/demography#45]
Hi Prof Hyndman, I noticed that NAs are introduced when read in the dataset using `hmd` method, it might because the HMD dataset now includes an age group which is named "110+", and when converting the 'age' column into a numeric vector, "110+" is converted into NA by coercion.

**Comment by robjhyndman** [comment]
The NAs in the returned object are actually when the rate is 0/0. However, there were some NA warnings produced which were misleading and are now suppressed in https://github.com/robjhyndman/demography/commit/9ffa6fa93119ff20840dbec8dfcda455f79f1101
