### ISSUE TITLE
hmd.mx import data doesn't seem to function even though I changed username and password

### ISSUE THREAD

**Issue by HassAG** [robjhyndman/demography#47]
the following code gives this error

```
hmd.mx(country = "JPN", username = "*********",password = "*******", label = "Japan") 

```

```
#####Error in hmd.mx(country = "JPN", username = "*********", password = "*******!",  : 
  Connection error at www.mortality.org. Please check username, password and country label.#####

```

Since Hmd have changed their interface website, I had to check-in with a new password  but I still can't import data from there using hmd.mx

**Comment by robjhyndman** [comment]
You need to update your package to the github version, and use your old username and password. We will update the package to the new HMD when they release their API.

**Comment by barbaraita** [comment]
I have the same issue. Did it update?

**Comment by barbaraita** [comment]
I have the same issue. You did not update, did you?

**Comment by barbaraita** [comment]
> @[barbaraita] No still the same even when I use the github version.

I'm trying to solve... I wrote this:
    path<-paste("https://www.mortality.org/Country/Country?cntr=",count,sep="")
    userpwd <- paste(username, ":", password, sep = "")
    txt <- RCurl::getURL(path, userpwd = userpwd)
    path2<-paste("https://www.mortality.org/File/GetDocument/hmd.v6/",count,"/STATS/Deaths_1x1.txt",sep="")
    con=url(path2,open="r") 
   #this the connection: A connection with                                                                                        
description "https://www.mortality.org/File/GetDocument/hmd.v6/ITA/STATS/Deaths_1x1.txt"
class       "url-libcurl"                                                               
mode        "r"                                                                         
text        "text"                                                                      
opened      "opened"                                                                    
can read    "yes"                                                                       
can write   "no" 

Then I have error, I am not able to go on...

**Comment by robjhyndman** [comment]
You need to use former.mortality.org instead of www.mortality.org.
The current github version of the package is working.
