### ISSUE TITLE
Forecasted kt value not according to expectation

### ISSUE THREAD

**Issue by Wilsonnn245** [robjhyndman/demography#52]
Hi, I'm facing an issue when forecasting mortality data using Lee-Carter. This is the R code I used:

![R Code](https://user-images.githubusercontent.com/127125706/226940942-f6b4054f-adf3-4eec-81fa-2ea558b8e610.png)

This is the re-adjusted kt output:

![image](https://user-images.githubusercontent.com/127125706/226941379-15190903-4c29-4eb8-b4ad-35167ba55a19.png)

Thus, I would expect the forecast kt at year 2001 to be around -15. However, the generated value is -0.55:

![image](https://user-images.githubusercontent.com/127125706/226942300-d140b741-8f11-423b-a86b-30757fc25732.png)

After doing some digging, I found that the forecast function changed my re-adjusted kt value:

![image](https://user-images.githubusercontent.com/127125706/226942572-82b7f9d3-3e3f-46e9-a602-5cc6ff0ab114.png)

I'm not sure what went wrong since the ax and bx values are unaffected. Would appreciate on any advice to get the expected forecast kt value. Thanks!

**Comment by robjhyndman** [comment]
You probably want to use `jumpchoice = "actual"` in `forecast()`. There are several variations on the Lee-Carter method, and the function tries to handle them all via the arguments.

**Comment by Wilsonnn245** [comment]
Yup, I already tried changing to `jumpchoice = "actual"` but it would still generate the same results as when I used `jumpchoice = "fit"`.

**Comment by robjhyndman** [comment]
Right, what is stored in the forecast object is an adjusted version of kt, with the last value subtracted. This makes the code simpler. It makes no difference to the final mx forecasts. If you want the forecasted kt values to match the fitted kt values, just add on the value at the end: 

```r
kt.f <- forecastItalyFemale$kt.f
last_kt <- c(tail(ItalylcaFemale$kt,1))
kt.f$x <- ItalylcaFemale$kt
kt.f$mean <- kt.f$mean + last_kt
kt.f$lower <- kt.f$lower + last_kt
kt.f$upper <- kt.f$upper + last_kt
plot(kt.f)
```

**Comment by Wilsonnn245** [comment]
It works perfectly now, appreciate your help!

I've also had another issue using the FDM model in 'demography' package. I've tried to simulate the results and compare it with a past research. When I plot the basis functions, the shape of the graphs are similar but the scaling is off. 

Reference:
![image](https://user-images.githubusercontent.com/127125706/227097869-1fc191ac-5d5a-4c0d-8edc-ffdf75a3172b.png)

Simulated Results:
![image](https://user-images.githubusercontent.com/127125706/227097993-833c0893-3058-4d94-a8fe-a5e9c1bde5b1.png)

R Code:
![image](https://user-images.githubusercontent.com/127125706/227098076-d6b50159-b658-41b4-bcd1-e7361d444a9e.png)
![image](https://user-images.githubusercontent.com/127125706/227098121-7a99ad6f-7664-4251-8e00-4149cf035e0a.png)

Is there something that I would have to amend? Or the scaling would not be a huge issue as long as the shape is similar? Thanks in advance!

**Comment by robjhyndman** [comment]
The scale factors are arbitrary -- if you multiply the basis function by k and divide the coefficient by k, you get the same result. For this reason, the basis functions are usually normalized in some way. Perhaps the normalization being used is different in the reference to the current version of the package.

**Comment by Wilsonnn245** [comment]
I see, that's great! Thanks for all the help and guidance Rob, really appreciate it <3
