### ISSUE TITLE
Generating AIC & BIC Criterion Using demography

### ISSUE THREAD

**Issue by Wilsonnn245** [robjhyndman/demography#53]
Hi Rob, 

I'm facing another issue where I can't seem to generate the AIC & BIC criterion due to object class. 
Here's the error message:
![image](https://user-images.githubusercontent.com/127125706/228331731-b80f6cfd-ec7e-41c9-9d9a-633d70bd7744.png)
![image](https://user-images.githubusercontent.com/127125706/228332395-68e8d317-ed86-45ef-8b84-4e93203060e1.png)

Should I calculate the criterion using another package? As it seems like other object classes (StMoMo, MortalityLaw) are able to generate AIC and BIC values.

Appreciate your input on the matter. Thanks!

**Comment by robjhyndman** [comment]
That information is not stored in the model objects.
