### ISSUE TITLE
increase HMDHFDplus min version soon

### ISSUE THREAD

**Issue by timriffe** [robjhyndman/demography#54]
Hi @robjhyndman 
I'm currently pushing HMDHFDplus version 2.0.3 to CRAN, it should be up in a day or two or three. I suggest you change the `DESCRIPTION` file text `HMDHFDplus (>= 2.0.0)` to `HMDHFDplus (>= 2.0.3)` once it's up on CRAN. The main fix is to include national subpopulations that weren't getting scraped in the previous update. e.g. Scotland.

**Comment by robjhyndman** [comment]
Thanks. Fixed in https://github.com/robjhyndman/demography/commit/8cee70debc251562c02ffdb3fe3044442a58b8ae
